#!/bin/sh
set -eu
i="$1"
case "$i" in 1|2|3|4|5|6|7|8|9|10) ;; *) exit 2 ;; esac
display=$((10 + i)); vnc=$((5900 + i))
if [ "$i" = 10 ]; then display=30; fi
set -- -display ":$display" -rfbport "$vnc" -localhost -nopw -forever -shared -noxdamage -wait 20 -defer 20
if [ -f "/run/huntly-vnc-viewonly/$i" ]; then set -- "$@" -viewonly -noclipboard; fi
exec /usr/bin/x11vnc "$@"
